/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#3d6568',
        'on-primary': '#ffffff',
        'primary-container': '#9ec8cb',
        'on-primary-container': '#2c5558',
        'primary-fixed': '#c0eaed',
        'primary-fixed-dim': '#a4ced1',
        'on-primary-fixed': '#002022',
        'on-primary-fixed-variant': '#244d50',
        'secondary': '#555f6f',
        'on-secondary': '#ffffff',
        'secondary-container': '#d6e0f3',
        'on-secondary-container': '#596373',
        'secondary-fixed': '#d9e3f6',
        'secondary-fixed-dim': '#bdc7d9',
        'on-secondary-fixed': '#121c2a',
        'on-secondary-fixed-variant': '#3d4756',
        'tertiary': '#4c6264',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#adc5c6',
        'on-tertiary-container': '#3c5254',
        'tertiary-fixed': '#cee7e8',
        'tertiary-fixed-dim': '#b3cbcc',
        'on-tertiary-fixed': '#071f20',
        'on-tertiary-fixed-variant': '#344b4c',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'surface': '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f4',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'surface-variant': '#e2e2e2',
        'surface-tint': '#3d6568',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#414849',
        'outline': '#717879',
        'outline-variant': '#c0c8c8',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f0f1f1',
        'inverse-primary': '#a4ced1',
        'background': '#f9f9f9',
        'on-background': '#1a1c1c',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1rem',
        'space-xl': '1.5rem',
        'gutter': '1rem',
        'gutter-mobile': '0.5rem',
        'margin': '1.5rem',
        'margin-mobile': '0.75rem',
      },
      fontFamily: {
        'space-mono': ['Space Mono', 'monospace'],
        'body-md': ['Space Mono', 'monospace'],
        'body-sm': ['Space Mono', 'monospace'],
        'body-lg': ['Space Mono', 'monospace'],
        'headline-sm': ['Space Mono', 'monospace'],
        'headline-md': ['Space Mono', 'monospace'],
        'headline-lg': ['Space Mono', 'monospace'],
        'headline-xl': ['Space Mono', 'monospace'],
        'label-sm': ['Space Mono', 'monospace'],
        'label-md': ['Space Mono', 'monospace'],
      },
      fontSize: {
        'body-sm': ['11px', { lineHeight: '16px', fontWeight: '400' }],
        'body-md': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'headline-sm': ['15px', { lineHeight: '22px', letterSpacing: '0.04em', fontWeight: '700' }],
        'headline-md': ['18px', { lineHeight: '26px', letterSpacing: '0.02em', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-xl': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      boxShadow: {
        'retro': '2px 2px 0px #1a1c1c',
        'retro-sm': '1px 1px 0px #1a1c1c',
        'retro-lg': '4px 4px 0px #1a1c1c',
        'retro-header': '0 2px 0px #1a1c1c',
        'retro-inset': 'inset 1px 1px 0 #1a1c1c',
      },
      animation: {
        'pulse-dot': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'blink': 'blink 1s step-end infinite',
        'scanline': 'scanline 8s linear infinite',
      },
      keyframes: {
        blink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        scanline: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100vh)' },
        },
      },
    },
  },
  plugins: [],
}
